# Tasks for managing our project

desc 'Print Hello World'
task :hello do 
	puts "Hello World"
end

desc "Runs a console"
task :console do
	require_relative "config/environment.rb"
	Pry.start
end

require "sinatra/activerecord/rake"

namespace :db do
	task :load_config do
		require "sinatra/activerecord"
	end
end